#!/usr/bin/env python
"""
Generates docs/field_catalog.md: for every column, which event_type actually populates it.

This is the guardrail for the class of bug that dominated the first full test-set pass.
Three separate queries silently returned 0 hits across all 20 matches because they filtered
a column on an event_type where it is always null (give_and_go on player_possession rather
than off_ball_run; interplayer_distance on on_ball_engagement; and so on). A boolean filter
against an all-null column is not an error - it is an empty result that looks like a
finding. The query-parsing stage cannot be allowed to guess here, so it should consult this
catalog before emitting a filter.

Also flags columns whose availability varies BY MATCH, not just by event type - e.g. the
roster's playing_time.sequences exists in only 11 of 20 matches while playing_time.total
exists in all 20. A column that is 100% populated in the match you prototype against can
be absent in the next one.

Usage:
    python scripts/field_catalog.py            # writes docs/field_catalog.md
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from enrich import DERIVED_COLUMNS, load_enriched  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "docs" / "field_catalog.md"
EVENT_TYPES = ["player_possession", "passing_option", "off_ball_run", "on_ball_engagement"]


def build(events: pd.DataFrame) -> pd.DataFrame:
    rows = []
    n_matches = events.match_id.nunique()
    for col in events.columns:
        if col.startswith("_"):
            continue
        rec = {"column": col,
               "derived": "yes" if col in DERIVED_COLUMNS else ""}
        for et in EVENT_TYPES:
            sub = events.loc[events.event_type == et, col]
            rec[et] = round(100.0 * sub.notna().mean(), 1) if len(sub) else 0.0
        per_match = events.groupby("match_id")[col].apply(lambda s: s.notna().any())
        rec["matches_with_any"] = f"{int(per_match.sum())}/{n_matches}"
        rows.append(rec)
    return pd.DataFrame(rows)


def main() -> None:
    events, _matches, _goals = load_enriched(verbose=True)
    cat = build(events)

    populated = cat[EVENT_TYPES].gt(0)
    single = cat[populated.sum(axis=1) == 1]
    partial = cat[cat.matches_with_any.str.split("/").apply(
        lambda p: int(p[0]) < int(p[1]))]

    lines = [
        "# Field Availability Catalog",
        "",
        "Generated by `scripts/field_catalog.py`. Percentages are the share of that",
        "event_type's rows where the column is non-null, over all 20 matches.",
        "",
        "**Read this before writing a filter.** A column that is always null for the",
        "event_type you are filtering returns zero rows silently - that is how three",
        "queries in the first full test-set pass produced empty results that looked like",
        "real findings rather than bugs.",
        "",
        f"- {len(cat)} columns total ({len(DERIVED_COLUMNS)} derived by `scripts/enrich.py`)",
        f"- {len(single)} columns are populated on exactly ONE event_type",
        f"- {len(partial)} columns are missing entirely from at least one match",
        "",
        "## Columns populated on exactly one event_type",
        "",
        "Filtering these on any other event_type yields an empty result, not an error.",
        "",
        "| Column | Only on | Coverage |",
        "|---|---|---|",
    ]
    for _, r in single.iterrows():
        et = [e for e in EVENT_TYPES if r[e] > 0][0]
        lines.append(f"| `{r['column']}` | {et} | {r[et]}% |")

    if len(partial):
        lines += [
            "",
            "## Columns absent from some matches entirely",
            "",
            "| Column | Matches with any value |",
            "|---|---|",
        ]
        for _, r in partial.iterrows():
            lines.append(f"| `{r['column']}` | {r['matches_with_any']} |")

    lines += [
        "",
        "## Full catalog",
        "",
        "| Column | Derived | player_possession | passing_option | off_ball_run | on_ball_engagement | Matches |",
        "|---|---|---|---|---|---|---|",
    ]
    for _, r in cat.iterrows():
        lines.append(
            f"| `{r['column']}` | {r['derived']} | {r['player_possession']}% | "
            f"{r['passing_option']}% | {r['off_ball_run']}% | "
            f"{r['on_ball_engagement']}% | {r['matches_with_any']} |")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[field_catalog] wrote {OUT} ({len(cat)} columns, "
          f"{len(single)} single-event-type, {len(partial)} match-partial)")


if __name__ == "__main__":
    main()
